// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  requestedBy: __t.identity().name("requested_by"),
  promptText: __t.string().name("prompt_text"),
  responseText: __t.string().name("response_text"),
  requestedType: __t.string().name("requested_type"),
  assistType: __t.string().name("assist_type"),
  policyStatus: __t.string().name("policy_status"),
  createdAt: __t.u64().name("created_at"),
});
