// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.u64().name("created_at"),
  kind: __t.string(),
  policy: __t.string(),
  selectedQuestionId: __t.string().name("selected_question_id"),
  editorMode: __t.string().name("editor_mode"),
  closedAt: __t.u64().name("closed_at"),
});
