// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AssistLog = __t.object("AssistLog", {
  id: __t.u64(),
  roomId: __t.u64(),
  requestedBy: __t.identity(),
  promptText: __t.string(),
  responseText: __t.string(),
  requestedType: __t.string(),
  assistType: __t.string(),
  policyStatus: __t.string(),
  createdAt: __t.u64(),
});
export type AssistLog = __Infer<typeof AssistLog>;

export const Document = __t.object("Document", {
  roomId: __t.u64(),
  content: __t.string(),
  updatedBy: __t.identity(),
  updatedAt: __t.u64(),
});
export type Document = __Infer<typeof Document>;

export const Participant = __t.object("Participant", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  active: __t.bool(),
  muted: __t.bool(),
  videoOff: __t.bool(),
  lastSeenAt: __t.u64(),
});
export type Participant = __Infer<typeof Participant>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  title: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.u64(),
});
export type Room = __Infer<typeof Room>;

export const RunOutput = __t.object("RunOutput", {
  id: __t.u64(),
  roomId: __t.u64(),
  seq: __t.u64(),
  stream: __t.string(),
  text: __t.string(),
  ts: __t.u64(),
});
export type RunOutput = __Infer<typeof RunOutput>;

export const SignalingMessage = __t.object("SignalingMessage", {
  id: __t.u64(),
  roomId: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  msgType: __t.string(),
  payload: __t.string(),
  createdAt: __t.u64(),
});
export type SignalingMessage = __Infer<typeof SignalingMessage>;

